# SPDX-FileCopyrightText: 2022 Friedrich-Alexander University Erlangen-Nürnberg (FAU)
#
# SPDX-License-Identifier: Apache-2.0

version: "3.7"
services:
  metabase:
    image: metabase/metabase
    ports:
      - 3000:3000
