version: '3'
services:

  database:
    image: "postgres" # use latest official postgres version
    container_name: pmt_db
    env_file:
      - .env # configure postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - datav2:/var/lib/postgresql/data/ # persist data even if container shuts down

#  server:
#    build:
#      dockerfile: Dockerfile
#      context: .
#    container_name: pmt_server
#    env_file:
#      - .env
#    ports:
#      - "8081:8081"
#    depends_on:
#      - database
#  metabase:
#    container_name: pmt_metabase
#    image: metabase/metabase
#    depends_on:
#      - database
#    ports:
#        - "3001:3000"
volumes:
  datav2: # named volumes can be managed easier using docker-compose
