version: '3'
services:
  # server:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   container_name: pmt_server 
  #   env_file:
  #     - .envlocal
  #   ports: 
  #       - "8081:8081"
  #   depends_on: 
  #     - database
  database:
    image: "postgres" # use latest official postgres version
    container_name: pmt_db
    env_file:
      - .env # configure postgres
    volumes:
      - data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
        - "5432:5432"
  metabase:
    container_name: pmt_metabase
    image: metabase/metabase
    depends_on:
      - database
    ports:
        - "3001:3000"
volumes:
  data: # named volumes can be managed easier using docker-compose
