# SPDX-FileCopyrightText: 2020 Friedrich-Alexander University Erlangen-Nürnberg (FAU)
#
# SPDX-License-Identifier: Apache-2.0

# Dummy container which provides a Composer result file.
FROM alpine:3.7

RUN apk --no-cache add curl

COPY example.json example.json
