# SPDX-FileCopyrightText: 2022 Friedrich-Alexander University Erlangen-Nürnberg (FAU)
#
# SPDX-License-Identifier: Apache-2.0

# Dummy container which provides a Composer result file.
FROM alpine:3.7

COPY example.json example.json
