// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bom.proto

package product

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InputType int32

const (
	InputType_SPDX   InputType = 0
	InputType_HUMAN  InputType = 1
	InputType_CUSTOM InputType = 2
)

var InputType_name = map[int32]string{
	0: "SPDX",
	1: "HUMAN",
	2: "CUSTOM",
}

var InputType_value = map[string]int32{
	"SPDX":   0,
	"HUMAN":  1,
	"CUSTOM": 2,
}

func (x InputType) String() string {
	return proto.EnumName(InputType_name, int32(x))
}

func (InputType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f689add15dae9986, []int{0}
}

type InputValue struct {
	FileName             string    `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Type                 InputType `protobuf:"varint,2,opt,name=type,proto3,enum=product.InputType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *InputValue) Reset()         { *m = InputValue{} }
func (m *InputValue) String() string { return proto.CompactTextString(m) }
func (*InputValue) ProtoMessage()    {}
func (*InputValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_f689add15dae9986, []int{0}
}

func (m *InputValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputValue.Unmarshal(m, b)
}
func (m *InputValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputValue.Marshal(b, m, deterministic)
}
func (m *InputValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputValue.Merge(m, src)
}
func (m *InputValue) XXX_Size() int {
	return xxx_messageInfo_InputValue.Size(m)
}
func (m *InputValue) XXX_DiscardUnknown() {
	xxx_messageInfo_InputValue.DiscardUnknown(m)
}

var xxx_messageInfo_InputValue proto.InternalMessageInfo

func (m *InputValue) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *InputValue) GetType() InputType {
	if m != nil {
		return m.Type
	}
	return InputType_SPDX
}

type Response struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Product              *Product `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f689add15dae9986, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto.RegisterEnum("product.InputType", InputType_name, InputType_value)
	proto.RegisterType((*InputValue)(nil), "product.InputValue")
	proto.RegisterType((*Response)(nil), "product.Response")
}

func init() {
	proto.RegisterFile("bom.proto", fileDescriptor_f689add15dae9986)
}

var fileDescriptor_f689add15dae9986 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xd7, 0x31, 0xb7, 0xe6, 0x89, 0x12, 0x9f, 0x97, 0x32, 0x2f, 0xa3, 0x07, 0x19, 0x43,
	0x76, 0xa8, 0xf8, 0x07, 0xb8, 0x7a, 0xd0, 0xc3, 0x66, 0x4d, 0x37, 0xf1, 0x26, 0x59, 0xf7, 0x84,
	0xc1, 0xd2, 0x84, 0x2c, 0x15, 0xf6, 0xdf, 0x8b, 0xa9, 0x29, 0x78, 0x4a, 0xf2, 0xe5, 0xbd, 0xdf,
	0xf7, 0xbd, 0x07, 0x6c, 0xab, 0xd5, 0xdc, 0x58, 0xed, 0x34, 0x8e, 0x8c, 0xd5, 0xbb, 0xa6, 0x72,
	0xe3, 0x8b, 0xbf, 0x4b, 0xab, 0xa7, 0x6f, 0x00, 0x2f, 0xb5, 0x69, 0xdc, 0xbb, 0x3c, 0x34, 0x84,
	0x37, 0xc0, 0xbe, 0xf6, 0x07, 0xfa, 0xac, 0xa5, 0xa2, 0x24, 0x9a, 0x44, 0x53, 0x26, 0xe2, 0x5f,
	0x61, 0x25, 0x15, 0xe1, 0x2d, 0x0c, 0xdc, 0xc9, 0x50, 0xd2, 0x9f, 0x44, 0xd3, 0xcb, 0x0c, 0xe7,
	0x01, 0xe4, 0xfb, 0xd7, 0x27, 0x43, 0xc2, 0xff, 0xa7, 0x05, 0xc4, 0x82, 0x8e, 0x46, 0xd7, 0x47,
	0xc2, 0x04, 0x46, 0x95, 0x25, 0xe9, 0x68, 0xe7, 0x71, 0xb1, 0x08, 0x4f, 0x9c, 0x41, 0x88, 0xe4,
	0x81, 0xe7, 0x19, 0xef, 0x80, 0x45, 0x7b, 0x8a, 0x50, 0x30, 0xbb, 0x03, 0xd6, 0x99, 0x60, 0x0c,
	0x83, 0xb2, 0x78, 0xfa, 0xe0, 0x3d, 0x64, 0x70, 0xf6, 0xbc, 0x59, 0x3e, 0xae, 0x78, 0x84, 0x00,
	0xc3, 0x7c, 0x53, 0xae, 0x5f, 0x97, 0xbc, 0x9f, 0xe5, 0x00, 0x0b, 0xad, 0x4a, 0xb2, 0xdf, 0xfb,
	0x8a, 0xf0, 0x01, 0x58, 0xee, 0x2d, 0x17, 0x5a, 0xe1, 0xf5, 0xff, 0xd0, 0x7e, 0xe8, 0xf1, 0x55,
	0x27, 0x86, 0xd8, 0x69, 0x6f, 0x3b, 0xf4, 0xeb, 0xb9, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x78,
	0x93, 0x34, 0xd8, 0x43, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BomServiceClient is the client API for BomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BomServiceClient interface {
	CreateBom(ctx context.Context, in *InputValue, opts ...grpc.CallOption) (*Response, error)
}

type bomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBomServiceClient(cc grpc.ClientConnInterface) BomServiceClient {
	return &bomServiceClient{cc}
}

func (c *bomServiceClient) CreateBom(ctx context.Context, in *InputValue, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/product.BomService/CreateBom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BomServiceServer is the server API for BomService service.
type BomServiceServer interface {
	CreateBom(context.Context, *InputValue) (*Response, error)
}

// UnimplementedBomServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBomServiceServer struct {
}

func (*UnimplementedBomServiceServer) CreateBom(ctx context.Context, req *InputValue) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBom not implemented")
}

func RegisterBomServiceServer(s *grpc.Server, srv BomServiceServer) {
	s.RegisterService(&_BomService_serviceDesc, srv)
}

func _BomService_CreateBom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).CreateBom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.BomService/CreateBom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).CreateBom(ctx, req.(*InputValue))
	}
	return interceptor(ctx, in, info, handler)
}

var _BomService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "product.BomService",
	HandlerType: (*BomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBom",
			Handler:    _BomService_CreateBom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bom.proto",
}
